version: '3.8'

services:
  security-db:
    image: postgres:16.1
    ports:
      - '2345:5432'
    environment:
      - POSTGRES_DB=security-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345

  security-redis:
    image: redis:6.0
    container_name: security-cache
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHALL,FLUSHDB

  security-service:
    build: security-service
    ports:
      - '9090:9090'
    depends_on:
      - security-db
      - security-redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://security-db:5432/security-service