version: '3.8'

services:
  security-service-db:
    image: postgres:16.1
    container_name: security-db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=security-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345

  security-service-redis:
    image: redis:6.0
    container_name: security-cache
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHALL,FLUSHDB

  security-service:
    build: security-service
    ports:
      - '9090:9090'
    depends_on:
      - security-service-db
      - security-service-redis